const nodemailer = require('nodemailer');
const { getDailyReport } = require('./reportService');
const { getSettings } = require('./settings');

function getTransporter() {
  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS } = process.env;
  if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS) {
    throw new Error('SMTP is not configured — set SMTP_HOST, SMTP_USER, SMTP_PASS in .env');
  }
  return nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT || '587'),
    secure: parseInt(SMTP_PORT || '587') === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS },
  });
}

function fmtTime(iso) {
  if (!iso) return '—';
  return new Date(iso).toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit', hour12: true, timeZone: 'Asia/Dhaka',
  });
}

function fmtDate(date) {
  return date.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', timeZone: 'Asia/Dhaka',
  });
}

function buildDailyReportHtml({ date, rows }) {
  const dateStr = fmtDate(date);

  const tableRows = rows.map(r => `
      <tr style="border-bottom:1px solid #f0f0f0;">
        <td style="padding:10px 12px;font-size:13px;color:#111827;font-weight:500;">${escapeHtml(r.employee.name)}</td>
        <td style="padding:10px 12px;font-size:13px;color:#6b7280;">${escapeHtml(r.employee.department || '—')}</td>
        <td style="padding:10px 12px;font-size:13px;color:#374151;">${fmtTime(r.firstPunch)}</td>
        <td style="padding:10px 12px;font-size:13px;color:#374151;">${r.delayMins > 0 ? r.delayMins + ' min' : '—'}</td>
      </tr>`).join('');

  return `
  <div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:#f3f4f6;padding:24px;">
    <div style="max-width:720px;margin:0 auto;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">
      <div style="background:#0f1629;padding:24px 28px;">
        <div style="font-size:12px;color:#93c5fd;font-weight:600;letter-spacing:.05em;text-transform:uppercase;">AttendTrack Pro</div>
        <div style="font-size:20px;color:#ffffff;font-weight:700;margin-top:4px;">Daily Attendance Report</div>
        <div style="font-size:13px;color:#cbd5e1;margin-top:2px;">${dateStr}</div>
      </div>

      <div style="padding:20px 24px 24px;">
        <table role="presentation" width="100%" style="border-collapse:collapse;">
          <thead>
            <tr style="border-bottom:2px solid #e5e7eb;">
              <th style="padding:10px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.03em;">Name</th>
              <th style="padding:10px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.03em;">Department</th>
              <th style="padding:10px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.03em;">Check-In</th>
              <th style="padding:10px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.03em;">Delay</th>
            </tr>
          </thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>

      <div style="padding:16px 24px;background:#f9fafb;border-top:1px solid #e5e7eb;">
        <div style="font-size:12px;color:#9ca3af;">This is an automated report generated by AttendTrack Pro. Please do not reply to this email.</div>
      </div>
    </div>
  </div>`;
}

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

async function sendDailyReportEmail({ date = new Date(), to } = {}) {
  let recipient = Array.isArray(to) ? to.join(',') : to;
  if (!recipient) {
    const settings = await getSettings();
    recipient = settings.report_recipients || process.env.REPORT_RECEIVER_EMAIL || '';
  }
  recipient = recipient.trim();
  if (!recipient) throw new Error('No recipient configured — add at least one recipient email in Settings.');

  const report = await getDailyReport(date);
  const html = buildDailyReportHtml(report);

  const transporter = getTransporter();
  const info = await transporter.sendMail({
    from: `"AttendTrack Pro" <${process.env.SMTP_USER}>`,
    to: recipient,
    subject: `Daily Attendance Report — ${fmtDate(report.date)}`,
    html,
  });

  return { messageId: info.messageId, recipient, summary: report.summary };
}

module.exports = { sendDailyReportEmail, buildDailyReportHtml };
